language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - pypy
    - pypy3

install:
    - "pip install sphinx"

script:
    - "python setup.py install"
    - "python test/test.py"
    - "cd doc_src"
    - "make doctest"

