language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

install:
    - "pip install sphinx"

script:
    - "python setup.py install"
    - "python test/test.py"
    - "cd doc_src"
    - "make doctest"

